// Code generated by xgen. DO NOT EDIT.

package etsi119612

// Qualifications ...
type Qualifications *QualificationsType

// QualificationsType ...
type QualificationsType struct {
	QualificationElement *QualificationElementType `xml:"QualificationElement"`
}

// QualificationElementType ...
type QualificationElementType struct {
	Qualifiers   *QualifiersType   `xml:"Qualifiers"`
	CriteriaList *CriteriaListType `xml:"CriteriaList"`
}

// CriteriaListType ...
type CriteriaListType struct {
	AssertAttr        string              `xml:"assert,attr,omitempty"`
	KeyUsage          []*KeyUsageType     `xml:"KeyUsage"`
	PolicySet         []*PoliciesListType `xml:"PolicySet"`
	CriteriaList      []*CriteriaListType `xml:"CriteriaList"`
	Description       string              `xml:"Description"`
	OtherCriteriaList *AnyType            `xml:"otherCriteriaList"`
}

// QualifiersType ...
type QualifiersType struct {
	Qualifier *QualifierType `xml:"Qualifier"`
}

// QualifierType ...
type QualifierType struct {
	UriAttr string `xml:"uri,attr,omitempty"`
}

// PoliciesListType ...
type PoliciesListType struct {
	PolicyIdentifier *ObjectIdentifierType `xml:"PolicyIdentifier"`
}

// KeyUsageType ...
type KeyUsageType struct {
	KeyUsageBit *KeyUsageBitType `xml:"KeyUsageBit"`
}

// KeyUsageBitType ...
type KeyUsageBitType struct {
	NameAttr string `xml:"name,attr,omitempty"`
	Value    bool   `xml:",chardata"`
}
