// Code generated by xgen. DO NOT EDIT.

package etsi119612

// InternationalNamesType ...
type InternationalNamesType struct {
	Name []*MultiLangNormStringType `xml:"Name"`
}

// MultiLangNormStringType ...
type MultiLangNormStringType struct {
	XmlLangAttr *Lang `xml:"xml:lang,attr"`
	*NonEmptyNormalizedString
}

// MultiLangStringType ...
type MultiLangStringType struct {
	XmlLangAttr *Lang `xml:"xml:lang,attr"`
	*NonEmptyString
}

// NonEmptyString ...
type NonEmptyString string

// NonEmptyNormalizedString ...
type NonEmptyNormalizedString string

// AddressType ...
type AddressType struct {
	TslPostalAddresses   *PostalAddressListType `xml:"tsl:PostalAddresses"`
	TslElectronicAddress *ElectronicAddressType `xml:"tsl:ElectronicAddress"`
}

// PostalAddresses ...
type PostalAddresses *PostalAddressListType

// PostalAddressListType ...
type PostalAddressListType struct {
	TslPostalAddress []*PostalAddressType `xml:"tsl:PostalAddress"`
}

// PostalAddress ...
type PostalAddress *PostalAddressType

// PostalAddressType ...
type PostalAddressType struct {
	XmlLangAttr     *Lang  `xml:"xml:lang,attr"`
	StreetAddress   string `xml:"StreetAddress"`
	Locality        string `xml:"Locality"`
	StateOrProvince string `xml:"StateOrProvince"`
	PostalCode      string `xml:"PostalCode"`
	CountryName     string `xml:"CountryName"`
}

// ElectronicAddress ...
type ElectronicAddress *ElectronicAddressType

// ElectronicAddressType ...
type ElectronicAddressType struct {
	URI []*NonEmptyMultiLangURIType `xml:"URI"`
}

// AnyType ...
type AnyType struct {
}

// Extension ...
type Extension *ExtensionType

// ExtensionType ...
type ExtensionType struct {
	CriticalAttr bool `xml:"Critical,attr"`
	*AnyType
}

// ExtensionsListType ...
type ExtensionsListType struct {
	TslExtension []*ExtensionType `xml:"tsl:Extension"`
}

// NonEmptyURIType ...
type NonEmptyURIType string

// AttributedNonEmptyURIType ...
type AttributedNonEmptyURIType struct {
	TypeAttr string `xml:"type,attr,omitempty"`
	Value    string `xml:",chardata"`
}

// NonEmptyMultiLangURIType ...
type NonEmptyMultiLangURIType struct {
	XmlLangAttr *Lang  `xml:"xml:lang,attr"`
	Value       string `xml:",chardata"`
}

// NonEmptyMultiLangURIListType ...
type NonEmptyMultiLangURIListType struct {
	URI []*NonEmptyMultiLangURIType `xml:"URI"`
}

// NonEmptyURIListType ...
type NonEmptyURIListType struct {
	URI []string `xml:"URI"`
}

// TrustServiceStatusList ...
type TrustServiceStatusList *TrustStatusListType

// TrustStatusListType ...
type TrustStatusListType struct {
	TSLTagAttr                  string                        `xml:"TSLTag,attr"`
	IdAttr                      string                        `xml:"Id,attr,omitempty"`
	TslSchemeInformation        *TSLSchemeInformationType     `xml:"tsl:SchemeInformation"`
	TslTrustServiceProviderList *TrustServiceProviderListType `xml:"tsl:TrustServiceProviderList"`
	DsSignature                 *Signature                    `xml:"ds:Signature"`
}

// TrustServiceProviderList ...
type TrustServiceProviderList *TrustServiceProviderListType

// TrustServiceProviderListType ...
type TrustServiceProviderListType struct {
	TslTrustServiceProvider []*TSPType `xml:"tsl:TrustServiceProvider"`
}

// SchemeInformation ...
type SchemeInformation *TSLSchemeInformationType

// TSLSchemeInformationType ...
type TSLSchemeInformationType struct {
	TSLVersionIdentifier        int                           `xml:"TSLVersionIdentifier"`
	TSLSequenceNumber           int                           `xml:"TSLSequenceNumber"`
	TslTSLType                  string                        `xml:"tsl:TSLType"`
	TslSchemeOperatorName       *InternationalNamesType       `xml:"tsl:SchemeOperatorName"`
	SchemeOperatorAddress       *AddressType                  `xml:"SchemeOperatorAddress"`
	TslSchemeName               *InternationalNamesType       `xml:"tsl:SchemeName"`
	TslSchemeInformationURI     *NonEmptyMultiLangURIListType `xml:"tsl:SchemeInformationURI"`
	StatusDeterminationApproach string                        `xml:"StatusDeterminationApproach"`
	TslSchemeTypeCommunityRules *NonEmptyMultiLangURIListType `xml:"tsl:SchemeTypeCommunityRules"`
	TslSchemeTerritory          string                        `xml:"tsl:SchemeTerritory"`
	TslPolicyOrLegalNotice      *PolicyOrLegalnoticeType      `xml:"tsl:PolicyOrLegalNotice"`
	HistoricalInformationPeriod int                           `xml:"HistoricalInformationPeriod"`
	TslPointersToOtherTSL       *OtherTSLPointersType         `xml:"tsl:PointersToOtherTSL"`
	ListIssueDateTime           string                        `xml:"ListIssueDateTime"`
	TslNextUpdate               *NextUpdateType               `xml:"tsl:NextUpdate"`
	TslDistributionPoints       *NonEmptyURIListType          `xml:"tsl:DistributionPoints"`
	SchemeExtensions            *ExtensionsListType           `xml:"SchemeExtensions"`
}

// TSLType ...
type TSLType string

// SchemeOperatorName ...
type SchemeOperatorName *InternationalNamesType

// SchemeName ...
type SchemeName *InternationalNamesType

// SchemeInformationURI ...
type SchemeInformationURI *NonEmptyMultiLangURIListType

// SchemeTypeCommunityRules ...
type SchemeTypeCommunityRules *NonEmptyMultiLangURIListType

// SchemeTerritory ...
type SchemeTerritory string

// PolicyOrLegalNotice ...
type PolicyOrLegalNotice *PolicyOrLegalnoticeType

// PolicyOrLegalnoticeType ...
type PolicyOrLegalnoticeType struct {
	TSLPolicy      []*NonEmptyMultiLangURIType `xml:"TSLPolicy"`
	TSLLegalNotice []*MultiLangStringType      `xml:"TSLLegalNotice"`
}

// NextUpdate ...
type NextUpdate *NextUpdateType

// NextUpdateType ...
type NextUpdateType struct {
	DateTime string `xml:"dateTime"`
}

// PointersToOtherTSL ...
type PointersToOtherTSL *OtherTSLPointersType

// OtherTSLPointersType ...
type OtherTSLPointersType struct {
	TslOtherTSLPointer []*OtherTSLPointerType `xml:"tsl:OtherTSLPointer"`
}

// OtherTSLPointer ...
type OtherTSLPointer *OtherTSLPointerType

// OtherTSLPointerType ...
type OtherTSLPointerType struct {
	TslServiceDigitalIdentities *ServiceDigitalIdentityListType `xml:"tsl:ServiceDigitalIdentities"`
	TSLLocation                 string                          `xml:"TSLLocation"`
	TslAdditionalInformation    *AdditionalInformationType      `xml:"tsl:AdditionalInformation"`
}

// ServiceDigitalIdentities ...
type ServiceDigitalIdentities *ServiceDigitalIdentityListType

// ServiceDigitalIdentityListType ...
type ServiceDigitalIdentityListType struct {
	TslServiceDigitalIdentity []*DigitalIdentityListType `xml:"tsl:ServiceDigitalIdentity"`
}

// AdditionalInformation ...
type AdditionalInformation *AdditionalInformationType

// AdditionalInformationType ...
type AdditionalInformationType struct {
	TextualInformation []*MultiLangStringType `xml:"TextualInformation"`
	OtherInformation   []*AnyType             `xml:"OtherInformation"`
}

// DistributionPoints ...
type DistributionPoints *NonEmptyURIListType

// TrustServiceProvider ...
type TrustServiceProvider *TSPType

// TSPType ...
type TSPType struct {
	TslTSPInformation *TSPInformationType  `xml:"tsl:TSPInformation"`
	TslTSPServices    *TSPServicesListType `xml:"tsl:TSPServices"`
}

// TSPInformation ...
type TSPInformation *TSPInformationType

// TSPInformationType ...
type TSPInformationType struct {
	TSPName                  *InternationalNamesType       `xml:"TSPName"`
	TSPTradeName             *InternationalNamesType       `xml:"TSPTradeName"`
	TSPAddress               *AddressType                  `xml:"TSPAddress"`
	TSPInformationURI        *NonEmptyMultiLangURIListType `xml:"TSPInformationURI"`
	TSPInformationExtensions *ExtensionsListType           `xml:"TSPInformationExtensions"`
}

// TSPServices ...
type TSPServices *TSPServicesListType

// TSPServicesListType ...
type TSPServicesListType struct {
	TslTSPService []*TSPServiceType `xml:"tsl:TSPService"`
}

// TSPService ...
type TSPService *TSPServiceType

// TSPServiceType ...
type TSPServiceType struct {
	TslServiceInformation *TSPServiceInformationType `xml:"tsl:ServiceInformation"`
	TslServiceHistory     *ServiceHistoryType        `xml:"tsl:ServiceHistory"`
}

// ServiceInformation ...
type ServiceInformation *TSPServiceInformationType

// TSPServiceInformationType ...
type TSPServiceInformationType struct {
	TslServiceTypeIdentifier     string                        `xml:"tsl:ServiceTypeIdentifier"`
	ServiceName                  *InternationalNamesType       `xml:"ServiceName"`
	TslServiceDigitalIdentity    *DigitalIdentityListType      `xml:"tsl:ServiceDigitalIdentity"`
	TslServiceStatus             string                        `xml:"tsl:ServiceStatus"`
	StatusStartingTime           string                        `xml:"StatusStartingTime"`
	SchemeServiceDefinitionURI   *NonEmptyMultiLangURIListType `xml:"SchemeServiceDefinitionURI"`
	TslServiceSupplyPoints       *ServiceSupplyPointsType      `xml:"tsl:ServiceSupplyPoints"`
	TSPServiceDefinitionURI      *NonEmptyMultiLangURIListType `xml:"TSPServiceDefinitionURI"`
	ServiceInformationExtensions *ExtensionsListType           `xml:"ServiceInformationExtensions"`
}

// ServiceStatus ...
type ServiceStatus string

// ServiceSupplyPoints ...
type ServiceSupplyPoints *ServiceSupplyPointsType

// ServiceSupplyPointsType ...
type ServiceSupplyPointsType struct {
	ServiceSupplyPoint *AttributedNonEmptyURIType `xml:"ServiceSupplyPoint"`
}

// ServiceTypeIdentifier ...
type ServiceTypeIdentifier string

// ServiceDigitalIdentity ...
type ServiceDigitalIdentity *DigitalIdentityListType

// DigitalIdentityListType ...
type DigitalIdentityListType struct {
	DigitalId []*DigitalIdentityType `xml:"DigitalId"`
}

// DigitalIdentityType ...
type DigitalIdentityType struct {
	X509Certificate string    `xml:"X509Certificate"`
	X509SubjectName string    `xml:"X509SubjectName"`
	DsKeyValue      *KeyValue `xml:"ds:KeyValue"`
	X509SKI         string    `xml:"X509SKI"`
	Other           *AnyType  `xml:"Other"`
}

// ServiceHistory ...
type ServiceHistory *ServiceHistoryType

// ServiceHistoryType ...
type ServiceHistoryType struct {
	TslServiceHistoryInstance []*ServiceHistoryInstanceType `xml:"tsl:ServiceHistoryInstance"`
}

// ServiceHistoryInstance ...
type ServiceHistoryInstance *ServiceHistoryInstanceType

// ServiceHistoryInstanceType ...
type ServiceHistoryInstanceType struct {
	TslServiceTypeIdentifier     string                   `xml:"tsl:ServiceTypeIdentifier"`
	ServiceName                  *InternationalNamesType  `xml:"ServiceName"`
	TslServiceDigitalIdentity    *DigitalIdentityListType `xml:"tsl:ServiceDigitalIdentity"`
	TslServiceStatus             string                   `xml:"tsl:ServiceStatus"`
	StatusStartingTime           string                   `xml:"StatusStartingTime"`
	ServiceInformationExtensions *ExtensionsListType      `xml:"ServiceInformationExtensions"`
}

// ExpiredCertsRevocationInfo ...
type ExpiredCertsRevocationInfo string

// AdditionalServiceInformation ...
type AdditionalServiceInformation *AdditionalServiceInformationType

// AdditionalServiceInformationType ...
type AdditionalServiceInformationType struct {
	URI              *NonEmptyMultiLangURIType `xml:"URI"`
	InformationValue string                    `xml:"InformationValue"`
	OtherInformation *AnyType                  `xml:"OtherInformation"`
}
